# Generated by Django 4.1.2 on 2023-11-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(blank=True, max_length=256, null=True)),
                ('company_name', models.CharField(blank=True, max_length=256, null=True)),
                ('company_domain', models.CharField(blank=True, max_length=256, null=True)),
                ('year_founded', models.CharField(blank=True, max_length=256, null=True)),
                ('industry', models.CharField(blank=True, max_length=256, null=True)),
                ('size_range', models.CharField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('country', models.CharField(blank=True, max_length=256, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=256, null=True)),
                ('current_employee_estimate', models.CharField(blank=True, max_length=256, null=True)),
                ('total_employee_estimate', models.CharField(blank=True, max_length=256, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
